"use client";
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Rotate3D,LocateFixed,Move,Plus,ZoomIn,ZoomOut} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {cupLayout} from '@/lib/cup-layout';
import {COSMETICS} from '@/lib/engagement';
import {ingredientGeometry} from './food-geometry';
import {drizzleGeometry} from './drizzle-geometry';
import {BASES,INGREDIENTS,type Bowl as BowlData} from '@/lib/game';
import type {BowlProps} from './bowl';
type Runtime={update:(bowl:BowlData,selected:number,animate:boolean)=>void;view:(rotate:boolean)=>void;reset:()=>void;zoom:(delta:number)=>void;dispose:()=>void};
export default function Bowl3D(props:BowlProps){
 const host=useRef<HTMLDivElement>(null),runtime=useRef<Runtime|null>(null),latest=useRef(props),rotateRef=useRef(false);latest.current=props;
 const [rotate,setRotate]=useState(false),[failed,setFailed]=useState(false),[ready,setReady]=useState(false);
 const interactive=!!(props.onPlace||props.onSelect),sealed=false;
 useEffect(()=>{
  if(!host.current)return;const el=host.current;let renderer:T.WebGLRenderer;
  try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setFailed(true);return;}
  renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,window.innerWidth<700?1.25:1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
  renderer.shadowMap.enabled=window.innerWidth>700;renderer.shadowMap.type=T.PCFShadowMap;renderer.domElement.setAttribute('aria-label','Interactive 3D layered açaí cup');renderer.domElement.tabIndex=0;el.appendChild(renderer.domElement);
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(37,1,.1,40);camera.position.set(3.4,2.9,6.8);
  const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.25,0);controls.enablePan=false;controls.enableDamping=false;controls.minDistance=5;controls.maxDistance=10;controls.minPolarAngle=.04;controls.maxPolarAngle=1.5;controls.enabled=!latest.current.onPlace&&!latest.current.onSelect;
  scene.add(new T.HemisphereLight('#fff4e9','#aaa0c7',1.9));const key=new T.DirectionalLight('#fff8ed',3);key.position.set(-3,7,4);key.castShadow=renderer.shadowMap.enabled;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-3;key.shadow.camera.right=3;key.shadow.camera.top=3;key.shadow.camera.bottom=-3;key.shadow.bias=-.003;key.shadow.normalBias=.025;scene.add(key);
  const fill=new T.DirectionalLight('#d5d5ff',1.7);fill.position.set(4,3,-3);scene.add(fill);
  const materials:T.Material[]=[],ownedGeometries:T.BufferGeometry[]=[];
  const mat=(opts:T.MeshPhysicalMaterialParameters)=>{const m=new T.MeshPhysicalMaterial(opts);materials.push(m);return m;};
  const ceramic=mat({color:'#ffffff',roughness:.07,clearcoat:1,clearcoatRoughness:.04,transparent:true,opacity:.10,depthWrite:false,side:T.DoubleSide,metalness:.05});
  const profile=[[.98,-1.12],[1.0,-1.08],[1.34,1.24],[1.36,1.29],[1.32,1.31],[1.30,1.24],[.96,-1.06]].map(([x,y])=>new T.Vector2(x,y));
  const ceramicGeo=new T.LatheGeometry(profile,96);ownedGeometries.push(ceramicGeo);const ceramicBowl=new T.Mesh(ceramicGeo,ceramic);ceramicBowl.renderOrder=5;scene.add(ceramicBowl);
  const rimMaterial=mat({color:'#ffffff',roughness:.1,transparent:true,opacity:.55,depthWrite:false,clearcoat:1});
  const rimGeo=new T.TorusGeometry(1.335,.026,12,96);ownedGeometries.push(rimGeo);const rim=new T.Mesh(rimGeo,rimMaterial);rim.rotation.x=Math.PI/2;rim.position.y=1.29;rim.renderOrder=6;scene.add(rim);
  const footGeo=new T.TorusGeometry(.99,.021,8,72);ownedGeometries.push(footGeo);const foot=new T.Mesh(footGeo,rimMaterial);foot.rotation.x=Math.PI/2;foot.position.y=-1.09;foot.renderOrder=6;scene.add(foot);
  const highlights=new T.Group();scene.add(highlights);for(const angle of [-1.1,1.3]){const pts=[];for(let i=0;i<=20;i++){const y=-1.02+i/20*2.17,r=1.01+(y+1.08)/2.32*.32;pts.push(new T.Vector3(Math.sin(angle)*r,y,Math.cos(angle)*r));}const g=new T.TubeGeometry(new T.CatmullRomCurve3(pts),24,.009,6,false);ownedGeometries.push(g);const strip=new T.Mesh(g,rimMaterial);strip.renderOrder=6;highlights.add(strip);}
  const baseMaterial=mat({color:'#75274c',roughness:.5,clearcoat:.25});const baseGeo=new T.CylinderGeometry(1.31,.99,2.3,96,4);ownedGeometries.push(baseGeo);const base=new T.Mesh(baseGeo,baseMaterial);base.visible=false;scene.add(base);
  const layerGroup=new T.Group();scene.add(layerGroup);const layerMeshes:T.Mesh[]=[];const bands:T.Mesh[]=[];
  const capMaterial=mat({vertexColors:true,roughness:.65,clearcoat:.08});
  const swirlMat=mat({color:'#a34273',roughness:.7});const swirl=new T.Group();scene.add(swirl);
  const shadowGeo=new T.CircleGeometry(1.7,64);ownedGeometries.push(shadowGeo);const shadowMat=new T.ShadowMaterial({opacity:.13});materials.push(shadowMat);const shadow=new T.Mesh(shadowGeo,shadowMat);shadow.rotation.x=-Math.PI/2;shadow.position.y=-1.14;shadow.receiveShadow=true;scene.add(shadow);
  const foodMat=mat({vertexColors:true,roughness:.42,clearcoat:.25,clearcoatRoughness:.3});const food=new T.Group();scene.add(food);const nodes=new Map<string,T.Mesh>();
  const ringGeo=new T.TorusGeometry(.55,.015,6,40);ownedGeometries.push(ringGeo);const ringMat=new T.MeshBasicMaterial({color:'#caff96',depthTest:false});materials.push(ringMat);const ring=new T.Mesh(ringGeo,ringMat);ring.rotation.x=-Math.PI/2;ring.visible=false;ring.renderOrder=9;scene.add(ring);
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let raf=0,visible=true,disposed=false,first=true,selected=-1,sealedBefore=false,baseLanding=0;const drops=new Map<string,{start:number;y:number;scale:number;scaleY:number;sauce:boolean}>();
  function frame(){raf=0;if(disposed||!visible)return;const now=performance.now();for(const [id,d] of drops){const mesh=nodes.get(id);if(!mesh){drops.delete(id);continue;}const t=Math.min(1,(now-d.start)/650);const bounce=t<.65?1-Math.pow(t/.65,2):Math.sin((t-.65)/.35*Math.PI)*-.08;mesh.position.y=d.y+(d.sauce?0:bounce*1.25);mesh.scale.setScalar(d.scale*(d.sauce?1:.92+.08*t));mesh.scale.y=d.scaleY*(d.sauce?1:.92+.08*t);if(d.sauce)mesh.scale.z=d.scale*Math.max(.01,1-Math.pow(1-t,3));if(t>=1){mesh.position.y=d.y;mesh.scale.setScalar(d.scale);mesh.scale.y=d.scaleY;drops.delete(id);}}
   if(baseLanding){const t=Math.min(1,(now-baseLanding)/550);base.position.y=.94+.7*Math.pow(1-t,2);if(t>=1)baseLanding=0;}renderer.render(scene,camera);renderer.domElement.dataset.drawCalls=String(renderer.info.render.calls);if(drops.size||baseLanding)raf=requestAnimationFrame(frame);
  }
  const render=()=>{if(!raf&&!disposed&&visible)raf=requestAnimationFrame(frame);};
  controls.addEventListener('change',render);
  const resize=()=>{const width=el.clientWidth,height=el.clientHeight;if(!width||!height)return;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();render();};const observer=new ResizeObserver(resize);observer.observe(el);
  const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)render();else if(raf){cancelAnimationFrame(raf);raf=0;}},{rootMargin:'100px'});intersection.observe(el);
  const visibility=()=>{visible=!document.hidden;if(visible)render();};document.addEventListener('visibilitychange',visibility);
  const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),.7),world=new T.Vector3();
  const point=(event:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const layer=Math.min(latest.current.activeLayer??0,(latest.current.bowl.layers?.length||1)-1);plane.constant=-cupLayout(latest.current.bowl.layers||[latest.current.bowl.base])[layer].top;const hit=ray.ray.intersectPlane(plane,world);if(!hit)return null;const x=50+hit.x/.031,y=50+hit.z/.031;const d=Math.hypot(x-50,y-50);if(d>46){const surface=ray.intersectObject(ceramicBowl,false)[0];if(!surface)return null;const sx=50+surface.point.x/.031,sy=50+surface.point.z/.031,sd=Math.hypot(sx-50,sy-50),sk=sd>34?34/sd:1;return {x:50+(sx-50)*sk,y:50+(sy-50)*sk};}const k=d>34?34/d:1;return {x:50+(x-50)*k,y:50+(y-50)*k};};
  let dragging:{index:number;node:T.Mesh|null;startX:number;startY:number;pointerId:number;point:{x:number;y:number};moved:boolean}|null=null;
  const down=(e:PointerEvent)=>{if(controls.enabled||e.button!==0||dragging)return;e.preventDefault();const pos=point(e);if(!pos)return;let index=-1,node:T.Mesh|null=null;if(latest.current.onSelect){const hit=ray.intersectObjects([...nodes.values()],false)[0];if(hit){node=hit.object as T.Mesh;index=node.userData.index;latest.current.onSelect(index);}}dragging={index,node,startX:e.clientX,startY:e.clientY,pointerId:e.pointerId,point:pos,moved:false};renderer.domElement.setPointerCapture(e.pointerId);};
  const move=(e:PointerEvent)=>{if(!dragging||e.pointerId!==dragging.pointerId)return;if(Math.hypot(e.clientX-dragging.startX,e.clientY-dragging.startY)>(e.pointerType==='touch'?18:12))dragging.moved=true;if(dragging.moved&&dragging.node&&latest.current.onMove){const p=point(e);if(p){const d=Math.hypot(p.x-50,p.y-50),k=d>36?36/d:1;dragging.node.position.x=(p.x-50)*k*.031;dragging.node.position.z=(p.y-50)*k*.031;ring.position.x=dragging.node.position.x;ring.position.z=dragging.node.position.z;render();}}};
  const up=(e:PointerEvent)=>{if(!dragging||e.pointerId!==dragging.pointerId)return;e.preventDefault();const p=point(e)||dragging.point,drag=dragging;dragging=null;if(p){if(drag.index>=0&&drag.moved){const d=Math.hypot(p.x-50,p.y-50),k=d>36?36/d:1;latest.current.onMove?.(drag.index,50+(p.x-50)*k,50+(p.y-50)*k);}else if(drag.index<0&&!drag.moved)latest.current.onPlace?.(p.x,p.y);}if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);};
  const cancel=()=>{dragging=null;runtime.current?.update(latest.current.bowl,latest.current.selectedIndex??-1,false);};
  const keyboard=(e:KeyboardEvent)=>{if((e.key==='Enter'||e.key===' ')&&!controls.enabled){e.preventDefault();latest.current.onPlace?.(50,50);}const p=latest.current.bowl.pieces[latest.current.selectedIndex??-1];if(p&&latest.current.onMove&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();let x=p.x+(e.key==='ArrowLeft'?-2:e.key==='ArrowRight'?2:0),y=p.y+(e.key==='ArrowUp'?-2:e.key==='ArrowDown'?2:0);const d=Math.hypot(x-50,y-50);if(d>36){x=50+(x-50)*36/d;y=50+(y-50)*36/d;}latest.current.onMove(latest.current.selectedIndex!,x,y);}};
  const lost=(event:Event)=>{event.preventDefault();setFailed(true);};renderer.domElement.addEventListener('webglcontextlost',lost);renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',cancel);renderer.domElement.addEventListener('keydown',keyboard);
  const update=(bowl:BowlData,index:number,animate:boolean)=>{
   const layers=bowl.layers||[bowl.base],layout=cupLayout(layers);ceramic.color.set('#ffffff');rimMaterial.color.set(COSMETICS.find(c=>c.id===bowl.finish)?.color||'#ffffff');
   for(const m of layerMeshes){layerGroup.remove(m);m.geometry.dispose();}layerMeshes.length=0;
   layers.forEach((kind,l)=>{const baseKind=BASES.find(b=>b.id===kind);if(!baseKind)return;const {bottom,top,height,r0,r1}=layout[l];const g=new T.CylinderGeometry(r1,r0,height-.012,72,8);const pos=g.getAttribute('position');const colors=new Float32Array(pos.count*3);const col=new T.Color(baseKind.color);for(let v=0;v<pos.count;v++){const variation=Math.abs(pos.getY(v))>height*.45?1:.96+.04*Math.sin(pos.getX(v)*4+pos.getY(v)*9+pos.getZ(v)*5);const radial=Math.hypot(pos.getX(v),pos.getZ(v));if(radial>.8){const wobble=1+.004*Math.sin(pos.getX(v)*15+pos.getY(v)*31+pos.getZ(v)*9);pos.setX(v,pos.getX(v)*wobble);pos.setZ(v,pos.getZ(v)*wobble);}colors[v*3]=col.r*variation;colors[v*3+1]=col.g*variation;colors[v*3+2]=col.b*variation;}g.setAttribute('color',new T.BufferAttribute(colors,3));const m=new T.Mesh(g,capMaterial);m.position.y=(bottom+top)/2;m.receiveShadow=false;layerGroup.add(m);layerMeshes.push(m);});
   const wanted=new Set<string>();bowl.pieces.forEach((p,i)=>{const uid=p.uid||String(i)+p.id;wanted.add(uid);const sauce=INGREDIENTS.find(t=>t.id===p.id)?.category==='Drizzle';const scale=p.size*.031,layer=Math.min(p.layer??layers.length-1,layers.length-1);const isBase=BASES.some(b=>b.id===layers[layer]),category=INGREDIENTS.find(t=>t.id===p.id)?.category,level=layout[layer];let y=isBase?level.top+.01:level.bottom+.035+(i%3)*Math.min(.045,level.height*.12);let overlaps=0;for(let j=0;j<i;j++){const prev=bowl.pieces[j];if((prev.layer??layers.length-1)===layer&&Math.hypot(prev.x-p.x,prev.y-p.y)<(prev.size+p.size)*.35)overlaps++;}y+=Math.min(overlaps,3)*.045;let mesh=nodes.get(uid),fresh=false;if(!mesh){mesh=new T.Mesh(ingredientGeometry(p.id),foodMat);mesh.castShadow=true;mesh.receiveShadow=true;food.add(mesh);nodes.set(uid,mesh);fresh=true;}else if(mesh.userData.ingredient!==p.id)mesh.geometry=ingredientGeometry(p.id);if(mesh.userData.customGeometry){mesh.geometry.dispose();mesh.geometry=ingredientGeometry(p.id);}
    if(sauce){const toppings=bowl.pieces.slice(0,i).filter(t=>(t.layer??layers.length-1)===layer&&INGREDIENTS.find(v=>v.id===t.id)?.category!=='Drizzle');const heights=toppings.map(t=>{const n=bowl.pieces.indexOf(t);return nodes.get(t.uid||String(n)+t.id)?.userData.restY??y;});mesh.geometry=drizzleGeometry(p,toppings,heights,0,{surface:y,radius:level.r1-.06,coordinateScale:.031});}mesh.userData={index:i,ingredient:p.id,customGeometry:!!sauce,restY:y,layer};mesh.position.set(sauce?0:(p.x-50)*.031,y,sauce?0:(p.y-50)*.031);const distance=Math.hypot(mesh.position.x,mesh.position.z),limit=level.r1-.04-scale*.48;if(distance>limit&&distance>0){mesh.position.x*=Math.max(.05,limit)/distance;mesh.position.z*=Math.max(.05,limit)/distance;}mesh.rotation.set(0,-p.rotation*Math.PI/180,0);if(!sauce){mesh.rotation.x=(i%3-1)*.08;mesh.rotation.z=(i%5-2)*.07;if(p.id==='banana'){mesh.rotation.x=.35;mesh.rotation.z=(i%2?1:-1)*.35;}}mesh.scale.setScalar(scale);if(!sauce&&layer<layers.length-1){mesh.geometry.computeBoundingBox();const height=mesh.geometry.boundingBox!.max.y;mesh.scale.y=Math.min(scale,(layer>=layers.length-2?.42:level.height*.8)/Math.max(.1,height));}if(fresh&&animate&&!first&&!reduced)drops.set(uid,{start:performance.now()+i%5*25,y,scale,scaleY:mesh.scale.y,sauce});});
   for(const [id,mesh] of nodes)if(!wanted.has(id)){food.remove(mesh);if(mesh.userData.customGeometry)mesh.geometry.dispose();nodes.delete(id);drops.delete(id);}food.visible=true;selected=index;ring.visible=index>=0&&index<bowl.pieces.length&&!sealed;if(ring.visible){const p=bowl.pieces[index],mesh=nodes.get(p.uid||String(index)+p.id)!;ring.position.copy(mesh.position);ring.position.y+=p.size*.031*.3;ring.scale.setScalar(p.size*.031);}
   sealedBefore=false;first=false;render();
  };
  runtime.current={update,view:(value)=>{controls.enabled=value||!latest.current.onPlace&&!latest.current.onSelect;render();},reset:()=>{camera.position.set(3.4,2.9,6.8);controls.target.set(0,.25,0);controls.update();render();},zoom:(delta)=>{const direction=camera.position.clone().sub(controls.target);const distance=T.MathUtils.clamp(direction.length()+delta,5,10);camera.position.copy(controls.target).add(direction.normalize().multiplyScalar(distance));controls.update();render();},dispose:()=>{disposed=true;cancelAnimationFrame(raf);observer.disconnect();intersection.disconnect();document.removeEventListener('visibilitychange',visibility);controls.dispose();layerMeshes.forEach(m=>m.geometry.dispose());nodes.forEach(mesh=>{if(mesh.userData.customGeometry)mesh.geometry.dispose();});materials.forEach(m=>m.dispose());ownedGeometries.forEach(g=>g.dispose());renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();}};
  update(latest.current.bowl,latest.current.selectedIndex??-1,false);resize();controls.update();setReady(true);
  return()=>{renderer.domElement.removeEventListener('webglcontextlost',lost);runtime.current?.dispose();runtime.current=null;};
 },[]);
 useEffect(()=>{runtime.current?.update(props.bowl,props.selectedIndex??-1,!!props.animatePlacements)},[props.bowl,props.selectedIndex,props.animatePlacements]);
 useEffect(()=>{rotateRef.current=rotate;runtime.current?.view(rotate)},[rotate,interactive]);
 useEffect(()=>{setRotate(false)},[props.interactionKey]);
 if(failed)return <div className="three-fallback" role="status"><p>Your browser could not open the 3D cup. Enable graphics acceleration or try another browser.</p><Button onClick={()=>window.location.reload()}>Reload 3D studio</Button></div>;
 return <div className={`three-bowl ${props.small?'three-small':''}`}><div ref={host} className={`bowl-art three-canvas ${rotate?'rotating':''}`} role="group" aria-label={props.label||'Layered açaí cup'}>{!ready&&<span className="three-loading">Setting the table…</span>}</div>{!props.small&&<div className="three-controls">{interactive&&!sealed&&<Button aria-pressed={!rotate} onClick={()=>setRotate(false)}>{props.onSelect?<Move size={14}/>:<Plus size={14}/>} {props.onSelect?'Edit':'Place'}</Button>}<Button aria-pressed={rotate||!interactive} onClick={()=>setRotate(!rotate)}><Rotate3D size={15}/>Rotate</Button><Button onClick={()=>runtime.current?.reset()} aria-label="Reset 3D view"><LocateFixed size={15}/></Button><Button onClick={()=>runtime.current?.zoom(-.7)} aria-label="Zoom in"><ZoomIn size={15}/></Button><Button onClick={()=>runtime.current?.zoom(.7)} aria-label="Zoom out"><ZoomOut size={15}/></Button></div>}<span className="three-hint">{props.small?'':rotate||!interactive?'Drag to orbit · zoom to explore':props.onSelect?'Drag a topping · arrow keys to nudge':'Tap to place in your selected layer · Enter to add at center'}</span></div>;
}
