"use client";
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Rotate3D,LocateFixed,Move,Plus,ZoomIn,ZoomOut} from 'lucide-react';
import {Button} from '@/components/ui/button';

import {COSMETICS} from '@/lib/engagement';
import {ingredientGeometry} from './food-geometry';
import {drizzleGeometry} from './drizzle-geometry';
import {BASES,INGREDIENTS,type Bowl as BowlData} from '@/lib/game';
import type {BowlProps} from './bowl';
type Runtime={update:(bowl:BowlData,selected:number,animate:boolean)=>void;view:(rotate:boolean)=>void;reset:()=>void;zoom:(delta:number)=>void;dispose:()=>void};
export default function Bowl3D(props:BowlProps){
 const host=useRef<HTMLDivElement>(null),runtime=useRef<Runtime|null>(null),latest=useRef(props),rotateRef=useRef(false);latest.current=props;
 const [rotate,setRotate]=useState(false),[failed,setFailed]=useState(false),[ready,setReady]=useState(false);
 const interactive=!!(props.onPlace||props.onSelect),sealed=props.bowl.gravity==='sealed';
 useEffect(()=>{
  if(!host.current)return;const el=host.current;let renderer:T.WebGLRenderer;
  try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setFailed(true);return;}
  renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,window.innerWidth<700?1.25:1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
  renderer.shadowMap.enabled=window.innerWidth>700;renderer.shadowMap.type=T.PCFShadowMap;renderer.domElement.setAttribute('aria-label','Interactive 3D açaí bowl');renderer.domElement.tabIndex=0;el.appendChild(renderer.domElement);
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(37,1,.1,40);camera.position.set(0,5.5,5.5);
  const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.23,0);controls.enablePan=false;controls.enableDamping=false;controls.minDistance=5;controls.maxDistance=10;controls.minPolarAngle=.04;controls.maxPolarAngle=1.25;controls.enabled=!latest.current.onPlace&&!latest.current.onSelect;
  scene.add(new T.HemisphereLight('#fff4e9','#aaa0c7',1.9));const key=new T.DirectionalLight('#fff8ed',3);key.position.set(-3,7,4);key.castShadow=renderer.shadowMap.enabled;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-3;key.shadow.camera.right=3;key.shadow.camera.top=3;key.shadow.camera.bottom=-3;key.shadow.bias=-.001;scene.add(key);
  const fill=new T.DirectionalLight('#d5d5ff',1.7);fill.position.set(4,3,-3);scene.add(fill);
  const materials:T.Material[]=[],ownedGeometries:T.BufferGeometry[]=[];
  const mat=(opts:T.MeshPhysicalMaterialParameters)=>{const m=new T.MeshPhysicalMaterial(opts);materials.push(m);return m;};
  const ceramic=mat({color:'#fdf8f3',roughness:.22,clearcoat:.8,clearcoatRoughness:.2,side:T.DoubleSide});
  const profile=[[0,-.48],[.9,-.48],[1.15,-.4],[1.5,-.12],[1.86,.38],[1.96,.58],[1.97,.65],[1.91,.69],[1.84,.65],[1.75,.42],[1.4,-.1],[1,-.34],[0,-.34]].map(([x,y])=>new T.Vector2(x,y));
  const ceramicGeo=new T.LatheGeometry(profile,72);ownedGeometries.push(ceramicGeo);const ceramicBowl=new T.Mesh(ceramicGeo,ceramic);ceramicBowl.receiveShadow=true;ceramicBowl.castShadow=true;scene.add(ceramicBowl);
  const rimGeo=new T.TorusGeometry(1.915,.048,12,72);ownedGeometries.push(rimGeo);const rim=new T.Mesh(rimGeo,ceramic);rim.rotation.x=Math.PI/2;rim.position.y=.65;scene.add(rim);
  const baseMaterial=mat({color:'#75274c',roughness:.35,clearcoat:.65,clearcoatRoughness:.25});const baseGeo=new T.SphereGeometry(1,64,24);ownedGeometries.push(baseGeo);const base=new T.Mesh(baseGeo,baseMaterial);base.scale.set(1.81,.14,1.81);base.position.y=.46;base.receiveShadow=true;scene.add(base);
  const spiral:T.Vector3[]=[];for(let i=0;i<180;i++){const a=i/179*Math.PI*7,r=.1+i/179*1.55;spiral.push(new T.Vector3(Math.cos(a)*r,.46+.14*Math.sqrt(Math.max(0,1-r*r/3.276))+.008,Math.sin(a)*r));}
  const swirlGeo=new T.TubeGeometry(new T.CatmullRomCurve3(spiral),180,.015,4,false);ownedGeometries.push(swirlGeo);const swirlMat=mat({color:'#c870a8',transparent:true,opacity:.28,roughness:.4});const swirl=new T.Mesh(swirlGeo,swirlMat);scene.add(swirl);
  const shadowGeo=new T.CircleGeometry(2.2,64);ownedGeometries.push(shadowGeo);const shadowMat=new T.ShadowMaterial({opacity:.13});materials.push(shadowMat);const shadow=new T.Mesh(shadowGeo,shadowMat);shadow.rotation.x=-Math.PI/2;shadow.position.y=-.49;shadow.receiveShadow=true;scene.add(shadow);
  const foodMat=mat({vertexColors:true,roughness:.42,clearcoat:.25,clearcoatRoughness:.4});const food=new T.Group();scene.add(food);const nodes=new Map<string,T.Mesh>();
  const ringGeo=new T.TorusGeometry(.55,.015,6,40);ownedGeometries.push(ringGeo);const ringMat=new T.MeshBasicMaterial({color:'#caff96',depthTest:false});materials.push(ringMat);const ring=new T.Mesh(ringGeo,ringMat);ring.rotation.x=-Math.PI/2;ring.visible=false;ring.renderOrder=9;scene.add(ring);
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let raf=0,visible=true,disposed=false,first=true,selected=-1,sealedBefore=false,baseLanding=0;const drops=new Map<string,{start:number;y:number;scale:number;sauce:boolean}>();
  function frame(){raf=0;if(disposed||!visible)return;const now=performance.now();for(const [id,d] of drops){const mesh=nodes.get(id);if(!mesh){drops.delete(id);continue;}const t=T.MathUtils.clamp((now-d.start)/(d.sauce?1150:720),0,1);const fall=Math.pow(1-Math.min(1,t/.72),3);const settle=t>.72?Math.sin((t-.72)/.28*Math.PI)*.045:0;mesh.position.y=d.y+(d.sauce?0:fall*1.1-settle);mesh.scale.setScalar(d.scale);if(!d.sauce){mesh.scale.y=d.scale*(1-settle*1.8);mesh.scale.x=d.scale*(1+settle*.7);mesh.scale.z=d.scale*(1+settle*.7);}else{const count=mesh.geometry.index?.count??mesh.geometry.getAttribute('position').count;mesh.geometry.setDrawRange(0,Math.min(count,Math.ceil(count*(t*t*(3-2*t))/48)*48));}if(t>=1){mesh.position.y=d.y;mesh.scale.setScalar(d.scale);if(d.sauce)mesh.geometry.setDrawRange(0,Infinity);drops.delete(id);}}

   if(baseLanding){const t=Math.min(1,(now-baseLanding)/550);base.position.y=.94+.7*Math.pow(1-t,2);if(t>=1)baseLanding=0;}renderer.render(scene,camera);renderer.domElement.dataset.drawCalls=String(renderer.info.render.calls);if(drops.size||baseLanding)raf=requestAnimationFrame(frame);
  }
  const render=()=>{if(!raf&&!disposed&&visible)raf=requestAnimationFrame(frame);};
  controls.addEventListener('change',render);
  const resize=()=>{const width=el.clientWidth,height=el.clientHeight;if(!width||!height)return;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();render();};const observer=new ResizeObserver(resize);observer.observe(el);
  const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)render();else if(raf){cancelAnimationFrame(raf);raf=0;}},{rootMargin:'100px'});intersection.observe(el);
  const visibility=()=>{visible=!document.hidden;if(visible)render();};document.addEventListener('visibilitychange',visibility);
  const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),-.62),world=new T.Vector3();
  const point=(event:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.ray.intersectPlane(plane,world);if(!hit)return null;const x=50+hit.x/.048,y=50+hit.z/.048;const d=Math.hypot(x-50,y-50);if(d>46)return null;const k=d>34?34/d:1;return {x:50+(x-50)*k,y:50+(y-50)*k};};
  let dragging:{index:number;node:T.Mesh|null;startX:number;startY:number;pointerId:number;point:{x:number;y:number};moved:boolean}|null=null;
  const down=(e:PointerEvent)=>{if(controls.enabled||e.button!==0||dragging)return;e.preventDefault();const pos=point(e);if(!pos)return;let index=-1,node:T.Mesh|null=null;if(latest.current.onSelect){const hit=ray.intersectObjects([...nodes.values()],false)[0];if(hit){node=hit.object as T.Mesh;index=node.userData.index;latest.current.onSelect(index);}}dragging={index,node,startX:e.clientX,startY:e.clientY,pointerId:e.pointerId,point:pos,moved:false};renderer.domElement.setPointerCapture(e.pointerId);};
  const move=(e:PointerEvent)=>{if(!dragging||e.pointerId!==dragging.pointerId)return;if(Math.hypot(e.clientX-dragging.startX,e.clientY-dragging.startY)>(e.pointerType==='touch'?18:12))dragging.moved=true;if(dragging.moved&&dragging.node&&latest.current.onMove){const p=point(e);if(p){const d=Math.hypot(p.x-50,p.y-50),k=d>36?36/d:1;dragging.node.position.x=(p.x-50)*k*.048;dragging.node.position.z=(p.y-50)*k*.048;ring.position.x=dragging.node.position.x;ring.position.z=dragging.node.position.z;render();}}};
  const up=(e:PointerEvent)=>{if(!dragging||e.pointerId!==dragging.pointerId)return;e.preventDefault();const p=point(e)||dragging.point,drag=dragging;dragging=null;if(p){if(drag.index>=0&&drag.moved){const d=Math.hypot(p.x-50,p.y-50),k=d>36?36/d:1;latest.current.onMove?.(drag.index,50+(p.x-50)*k,50+(p.y-50)*k);}else if(drag.index<0&&!drag.moved)latest.current.onPlace?.(p.x,p.y);}if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);};
  const cancel=()=>{dragging=null;runtime.current?.update(latest.current.bowl,latest.current.selectedIndex??-1,false);};
  const keyboard=(e:KeyboardEvent)=>{if((e.key==='Enter'||e.key===' ')&&!controls.enabled){e.preventDefault();latest.current.onPlace?.(50,50);}const p=latest.current.bowl.pieces[latest.current.selectedIndex??-1];if(p&&latest.current.onMove&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();let x=p.x+(e.key==='ArrowLeft'?-2:e.key==='ArrowRight'?2:0),y=p.y+(e.key==='ArrowUp'?-2:e.key==='ArrowDown'?2:0);const d=Math.hypot(x-50,y-50);if(d>36){x=50+(x-50)*36/d;y=50+(y-50)*36/d;}latest.current.onMove(latest.current.selectedIndex!,x,y);}};
  const lost=(event:Event)=>{event.preventDefault();setFailed(true);};renderer.domElement.addEventListener('webglcontextlost',lost);renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',cancel);renderer.domElement.addEventListener('keydown',keyboard);
  const update=(bowl:BowlData,index:number,animate:boolean)=>{
   ceramic.color.set(COSMETICS.find(c=>c.id===bowl.finish)?.color||'#fdf8f3');const baseColor=BASES.find(b=>b.id===bowl.base)?.color||'#75274c';baseMaterial.color.set(baseColor);swirlMat.color.set(baseColor).lerp(new T.Color('#ffcbf0'),.35);const gravity=bowl.gravity;const sealed=gravity==='sealed';base.position.y=sealed?.94:.46;baseMaterial.transparent=!!gravity&&!sealed;baseMaterial.opacity=gravity&&!sealed?.25:1;swirl.visible=!gravity||sealed;swirl.position.y=sealed?.48:0;
   const wanted=new Set<string>();let highest=.63;bowl.pieces.forEach((p,i)=>{const uid=p.uid||String(i)+p.id;wanted.add(uid);const sauce=INGREDIENTS.find(t=>t.id===p.id)?.category==='Drizzle';const scale=p.size*.048;let y=.61;let overlaps=0;for(let j=0;j<i;j++){const prev=bowl.pieces[j];if(Math.hypot(prev.x-p.x,prev.y-p.y)<(prev.size+p.size)*.28)overlaps++;}y+=Math.min(overlaps,8)*.028;if(sauce)y=Math.min(.86,highest+.02);else highest=Math.max(highest,y+scale*.28);let mesh=nodes.get(uid),fresh=false;if(!mesh){mesh=new T.Mesh(ingredientGeometry(p.id),foodMat);mesh.castShadow=true;mesh.receiveShadow=true;food.add(mesh);nodes.set(uid,mesh);fresh=true;}else if(mesh.userData.ingredient!==p.id)mesh.geometry=ingredientGeometry(p.id);if(mesh.userData.customGeometry){mesh.geometry.dispose();mesh.geometry=ingredientGeometry(p.id);}
    if(sauce){const toppings=bowl.pieces.slice(0,i).filter(t=>INGREDIENTS.find(v=>v.id===t.id)?.category!=='Drizzle');const heights=toppings.map(t=>{const n=bowl.pieces.indexOf(t);return nodes.get(t.uid||String(n)+t.id)?.userData.restY??.61;});mesh.geometry=drizzleGeometry(p,toppings,heights,i-toppings.length);y=.61;}mesh.userData={index:i,ingredient:p.id,customGeometry:!!sauce,restY:y};mesh.position.set(sauce?0:(p.x-50)*.048,y,sauce?0:(p.y-50)*.048);mesh.rotation.y=-p.rotation*Math.PI/180;mesh.scale.setScalar(scale);if(fresh&&animate&&!first&&!reduced){drops.set(uid,{start:performance.now()+i%5*25,y,scale,sauce});if(sauce)mesh.geometry.setDrawRange(0,0);else mesh.position.y=y+1.1;}else if(drops.has(uid)){const d=drops.get(uid)!;d.y=y;d.scale=scale;}});
   for(const [id,mesh] of nodes)if(!wanted.has(id)){food.remove(mesh);if(mesh.userData.customGeometry)mesh.geometry.dispose();nodes.delete(id);drops.delete(id);}food.visible=true;selected=index;ring.visible=index>=0&&index<bowl.pieces.length&&!sealed;if(ring.visible){const p=bowl.pieces[index],mesh=nodes.get(p.uid||String(index)+p.id)!;ring.position.copy(mesh.position);ring.position.y+=p.size*.048*.3;ring.scale.setScalar(p.size*.048);}
   if(sealed&&!sealedBefore&&animate&&!reduced){baseLanding=performance.now();}sealedBefore=sealed;first=false;render();
  };
  runtime.current={update,view:(value)=>{controls.enabled=value||!latest.current.onPlace&&!latest.current.onSelect;render();},reset:()=>{camera.position.set(0,5.5,5.5);controls.target.set(0,.23,0);controls.update();render();},zoom:(delta)=>{const direction=camera.position.clone().sub(controls.target);const distance=T.MathUtils.clamp(direction.length()+delta,5,10);camera.position.copy(controls.target).add(direction.normalize().multiplyScalar(distance));controls.update();render();},dispose:()=>{disposed=true;cancelAnimationFrame(raf);observer.disconnect();intersection.disconnect();document.removeEventListener('visibilitychange',visibility);controls.dispose();nodes.forEach(mesh=>{if(mesh.userData.customGeometry)mesh.geometry.dispose();});materials.forEach(m=>m.dispose());ownedGeometries.forEach(g=>g.dispose());renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();}};
  update(latest.current.bowl,latest.current.selectedIndex??-1,false);resize();controls.update();setReady(true);
  return()=>{renderer.domElement.removeEventListener('webglcontextlost',lost);runtime.current?.dispose();runtime.current=null;};
 },[]);
 useEffect(()=>{runtime.current?.update(props.bowl,props.selectedIndex??-1,!!props.animatePlacements)},[props.bowl,props.selectedIndex,props.animatePlacements]);
 useEffect(()=>{rotateRef.current=rotate;runtime.current?.view(rotate)},[rotate,interactive]);
 useEffect(()=>{setRotate(false)},[props.interactionKey]);
 if(failed)return <div className="three-fallback"><p>3D needs hardware acceleration. Enable it in your browser settings, then reload the game.</p></div>;
 return <div className={`three-bowl ${props.small?'three-small':''}`}><div ref={host} className={`bowl-art three-canvas ${rotate?'rotating':''}`} role="group" aria-label={props.label||'3D açaí bowl'}>{!ready&&<span className="three-loading">Setting the table…</span>}</div>{!props.small&&<div className="three-controls">{interactive&&!sealed&&<Button aria-pressed={!rotate} onClick={()=>setRotate(false)}>{props.onSelect?<Move size={14}/>:<Plus size={14}/>} {props.onSelect?'Edit':'Place'}</Button>}<Button aria-pressed={rotate||!interactive} onClick={()=>setRotate(!rotate)}><Rotate3D size={15}/>Rotate</Button><Button onClick={()=>runtime.current?.reset()} aria-label="Reset 3D view"><LocateFixed size={15}/></Button><Button onClick={()=>runtime.current?.zoom(-.7)} aria-label="Zoom in"><ZoomIn size={15}/></Button><Button onClick={()=>runtime.current?.zoom(.7)} aria-label="Zoom out"><ZoomOut size={15}/></Button></div>}<span className="three-hint">{props.small?'':rotate||!interactive?'Drag to orbit · zoom to explore':props.onSelect?'Drag a topping · arrow keys to nudge':'Tap to place · Enter to add at center'}</span></div>;
}
