"use client";
import {Layers,Plus,ArrowUp,ArrowDown,Trash2,Check} from 'lucide-react';
import {Button} from './ui/button';
import {BASES,INGREDIENTS,MAX_PIECES,bowlCost,type Bowl} from '@/lib/game';
export function CupLayers({bowl,active,selected,disabled,budget,onActive,onChange}:{bowl:Bowl;active:number;selected:string;disabled:boolean;budget:number|null;onActive:(i:number)=>void;onChange:(b:Bowl)=>void}){
 const layers=bowl.layers||[bowl.base],index=Math.min(active,layers.length-1),ingredient=INGREDIENTS.find(i=>i.id===selected),name=(id:string)=>BASES.find(b=>b.id===id)?.name||INGREDIENTS.find(i=>i.id===id)?.name||id;
 const full=layers.reduce((sum,id,i)=>sum+(BASES.some(b=>b.id===id)?1:Math.min(1,bowl.pieces.filter(p=>(p.layer??layers.length-1)===i).length/12)),0);
 const add=(id:string)=>{if(disabled||layers.length>=6)return;onChange({...bowl,layers:[...layers,id]});onActive(layers.length)};
 const fill=()=>{if(disabled||!ingredient)return;const room=MAX_PIECES-bowl.pieces.length,n=Math.min(12,room,budget===null?12:Math.floor((budget-bowlCost(bowl))/ingredient.price));if(n<1)return;const pieces=Array.from({length:n},(_,i)=>{const a=i*2.39996+Math.random()*.3,r=i===0?0:13+Math.sqrt(i/12)*18;return {id:ingredient.id,uid:crypto.randomUUID(),layer:index,x:50+Math.cos(a)*r,y:50+Math.sin(a)*r,size:ingredient.category==='Drizzle'?38:ingredient.category==='Crunch'?15:20,rotation:i*37+Math.random()*15};});onChange({...bowl,layers:layers.map((id,i)=>i===index?ingredient.id:id),pieces:[...bowl.pieces,...pieces]});};
 const swap=(direction:number)=>{const j=index+direction;if(j<0||j>=layers.length)return;const reordered=[...layers];[reordered[index],reordered[j]]=[reordered[j],reordered[index]];onChange({...bowl,layers:reordered,pieces:bowl.pieces.map(p=>{const layer=p.layer??layers.length-1;return {...p,layer:layer===index?j:layer===j?index:layer}})});onActive(j)};
 const remove=()=>{if(layers.length===1)return;onChange({...bowl,layers:layers.filter((_,i)=>i!==index),pieces:bowl.pieces.filter(p=>(p.layer??layers.length-1)!==index).map(p=>({...p,layer:(p.layer??layers.length-1)>index?(p.layer??layers.length-1)-1:p.layer??layers.length-1}))});onActive(Math.max(0,index-1))};
 return <section className="cup-layers"><div className="panel-heading"><h3><Layers size={18}/>Build your layers</h3><strong>{Math.round(full/6*100)}% filled</strong></div><div className="cup-fill-track"><span style={{width:`${full/6*100}%`}}/></div><div className="layer-chips">{layers.map((id,i)=><Button key={i} aria-pressed={index===i} onClick={()=>onActive(i)} disabled={disabled}><span>{i+1}</span>{name(id)}{index===i&&<Check size={13}/>}</Button>)}</div><p>Bottom → top. Fill replaces the selected layer’s base with ingredients. Stack up to six layers.</p><div className="layer-actions"><Button disabled={disabled||layers.length>=6||!ingredient} onClick={()=>add(ingredient!.id)}><Plus size={15}/>New {ingredient?.name||'ingredient'} layer</Button><Button disabled={disabled||layers.length>=6} onClick={()=>add(bowl.base)}>Pour açaí layer</Button><Button className="primary" disabled={disabled||!ingredient||bowl.pieces.length>=MAX_PIECES||budget!==null&&bowlCost(bowl)+ingredient.price>budget} onClick={fill}>Fill with {ingredient?.name||'ingredient'}{budget!==null&&ingredient?` · up to ${Math.min(12,Math.floor((budget-bowlCost(bowl))/ingredient.price))} pieces`:''}</Button></div><div className="layer-reorder"><Button aria-label="Move layer down" disabled={disabled||index===0} onClick={()=>swap(-1)}><ArrowDown size={15}/></Button><Button aria-label="Move layer up" disabled={disabled||index===layers.length-1} onClick={()=>swap(1)}><ArrowUp size={15}/></Button><Button disabled={disabled||layers.length===1} onClick={remove}><Trash2 size={14}/>Remove layer</Button><span>Layer {index+1} selected{layers.length===6?' · cup reaches the rim':''}</span></div></section>;
}
