"use client";
import {useEffect,useState} from 'react';
import {Target,Check,Sparkles,Lock,Palette,Timer,Zap} from 'lucide-react';
import {Button} from './ui/button';
import {Bowl} from './bowl';
import {GOALS,goalProgress,ROUND_MODES,REACTIONS,COSMETICS,similarity,type RoundMode} from '@/lib/engagement';
import {SURPRISE_DELAY_MS} from '@/lib/studio';
import type {Bowl as BowlData,View} from '@/lib/game';

export function RoundSettings({room,busy,onChange}:{room:View;busy:boolean;onChange:(settings:{roundSeconds?:number;modes?:(RoundMode|'random')[]})=>void}){const disabled=busy||room.host!==room.me;return <section className="party-settings"><div><p className="eyebrow">SET THE PACE</p><h2>Your party. Your menu.</h2><p>Private goals · surprise after 60s · reactions at the reveal</p></div><fieldset disabled={disabled}><legend><Timer size={17}/>Studio timer</legend><div className="pace-buttons">{[105,180,300].map(n=><Button key={n} aria-pressed={room.roundSeconds===n} onClick={()=>onChange({roundSeconds:n})}>{n===300?'5:00':n===180?'3:00':'1:45'}</Button>)}</div><p>Five minutes is the full cooking experience. Shorter timers are optional.</p></fieldset><div className="mode-picker">{room.modes.map((mode,i)=><label key={i}>Round {i+1}<select aria-label={`Round ${i+1} game mode`} value={mode} disabled={disabled} onChange={e=>onChange({modes:room.modes.map((m,j)=>j===i?e.target.value as RoundMode|'random':m)})}><option value="random">Random mode</option>{ROUND_MODES.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><span>{mode==='random'?'A surprise mode is picked when this round begins.':ROUND_MODES.find(m=>m.id===mode)?.description}</span></label>)}</div></section>}
export function MissionBoard({room,bowl,now}:{room:View|null;bowl:BowlData;now:number}){const goal=GOALS.find(g=>g.id===room?.myGoal),progress=goal?goalProgress(bowl,goal.id):null,mode=ROUND_MODES.find(m=>m.id===room?.roundMode);return <div className="mission-grid">{room&&mode&&<div className="mode-banner"><Zap size={23}/><div><strong>{mode.name}</strong><p>{mode.description}</p></div></div>}{goal&&progress&&<section className={`secret-goal ${progress.complete?'goal-complete':''}`}><div className="mission-heading"><Target/><span>YOUR SECRET GOAL <small>+1 point</small></span>{progress.complete&&<Check/>}</div><h3>{goal.name}</h3><p>{goal.description}</p><div className="mission-track"><span style={{width:`${progress.value/progress.target*100}%`}}/></div><span>{progress.complete?'Goal complete! Keep it in your final bowl.':`${progress.value}/${progress.target} · only you can see this goal`}</span></section>}{room?.startedAt&&<section className={`surprise-card ${room.surprise?'surprise-revealed':''}`}><Sparkles/><div><strong>{room.surprise?'SURPRISE: SIGNATURE SERVE':'A surprise is on its way…'}</strong><p>{room.surprise||`Reveals 60 seconds into the round. ${Math.max(0,Math.ceil((room.startedAt+SURPRISE_DELAY_MS-now)/1000))}s to go.`}</p>{room.surprise&&<span>{bowl.title.trim().length>=3?'✓ Bonus ready · +1 point':'Give your bowl a name below.'}</span>}</div></section>}{room?.reference&&<section className="copy-reference"><div><p className="eyebrow">THE MIRROR MENU</p><h3>Study it. Recreate it.</h3><p>Match the base, ingredient types, sizes, and positions. Extra pieces reduce similarity.</p><strong>{similarity(bowl,room.reference)}% match <small>75% earns +2</small></strong></div><Bowl bowl={room.reference} small/></section>}</div>}
export function RevealReactions({room,ballot,mine,onReact}:{room:View;ballot:string;mine:boolean;onReact:(kind:string)=>void}){const [pending,setPending]=useState(false),[tapped,setTapped]=useState<string|null>(null);useEffect(()=>{if(!tapped)return;const timer=setTimeout(()=>setTapped(null),800);return()=>clearTimeout(timer)},[tapped]);const sent=room.myReacted.includes(ballot);return <div className="reveal-reactions"><div className="reaction-floats" aria-live="polite">{room.reactions.filter(r=>r.ballot===ballot).map(r=><div key={r.id} className={`reaction-burst reaction-${r.kind}`} aria-label={REACTIONS.find(v=>v.id===r.kind)?.name}>{Array.from({length:5},(_,i)=><span key={i} className={`reaction-particle particle-${i}`} aria-hidden="true">{REACTIONS.find(v=>v.id===r.kind)?.emoji}</span>)}</div>)}</div><span>{mine?'Enjoy the love from your table':sent?'Reaction sent!':'Send a little love · reactions don’t score'}</span><div>{REACTIONS.map(r=><Button key={r.id} className={tapped===r.id?'reaction-tapped':''} aria-label={`${r.name} reaction`} disabled={mine||sent||pending} onClick={async()=>{setTapped(r.id);setPending(true);try{await onReact(r.id)}finally{setPending(false)}}}>{r.emoji}</Button>)}</div></div>}
export function BonusResults({room}:{room:View}){return <section className="bonus-results"><p className="eyebrow">EXTRA FLAVOR</p><h2>Challenge points</h2><div>{room.entries.map(e=><article key={e.ballot}><strong>{e.name}{e.mine?' · you':''}</strong><p>{GOALS.find(g=>g.id===e.goal)?.name||'No secret goal'}</p><span>Goal +{e.bonuses?.goal||0} · Signature +{e.bonuses?.surprise||0} · Order +{e.bonuses?.order||0} · Twist +{e.bonuses?.twist||0}{room.roundMode==='copy'?` · Mirror +${e.bonuses?.copy||0}`:''}</span></article>)}</div></section>}
export function CosmeticShelf({room,onChoose}:{room:View|null;onChoose:(finish:string)=>void}){const [games,setGames]=useState(0),[finish,setFinish]=useState('porcelain'),[open,setOpen]=useState(false),[unlocked,setUnlocked]=useState('');useEffect(()=>{try{const stats=JSON.parse(localStorage.getItem('acai-collection')||'{"matches":[]}');setGames(stats.matches.length);setFinish(localStorage.getItem('acai-finish')||'porcelain')}catch{}},[]);useEffect(()=>{if(room?.phase!=='final')return;try{const stats=JSON.parse(localStorage.getItem('acai-collection')||'{"matches":[]}');const id=`${room.code}:${room.matchId}`;if(!stats.matches.includes(id)){stats.matches.push(id);localStorage.setItem('acai-collection',JSON.stringify(stats));setGames(stats.matches.length);const reward=COSMETICS.find(c=>c.games===stats.matches.length);if(reward){setUnlocked(reward.name);setOpen(true)}}}catch{}},[room?.phase,room?.matchId,room?.code]);return <section className="cosmetic-shelf"><Button aria-expanded={open} onClick={()=>setOpen(!open)}><Palette size={18}/>Your bowl collection <span>{games} completed {games===1?'game':'games'}</span></Button>{unlocked&&<p className="unlock-notice"><Sparkles size={18}/>{unlocked} unlocked! A new look for your next creation.</p>}{open&&<><p>Finish multiplayer games to unlock colors. Saved on this device. Every ingredient is always available.</p><div>{COSMETICS.map(c=><Button key={c.id} className="cosmetic-option" disabled={games<c.games} aria-pressed={finish===c.id} onClick={()=>{setFinish(c.id);localStorage.setItem('acai-finish',c.id);onChoose(c.id)}}><i style={{background:c.color}}/><strong>{c.name}</strong><span>{games<c.games?<><Lock size={13}/>{c.games} {c.games===1?'game':'games'}</>:finish===c.id?'Selected':'Wear it'}</span></Button>)}</div></>}</section>}
