"use client";
import {useEffect,useState,type ReactNode} from 'react';
import {Star,Search,Check,Lock} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {IngredientImage} from './bowl';
import {INGREDIENTS,type View} from '@/lib/game';
import {FANTASY_BY_ID,SAUCE_COLORS} from '@/lib/fantasy-ingredients';
function Picture({id}:{id:string}){const i=INGREDIENTS.find(v=>v.id===id);if(!i)return null;return i.category==='Drizzle'?<span className={`drizzle-swatch ingredient-sauce-preview ${id}`} style={{color:SAUCE_COLORS[id]}}><span/><span/><span/></span>:<IngredientImage index={i.sprite}/>}
export function IngredientBrowser({category,collection,selected,disabled,canChoose,onChoose,budget,room,children}:{category:string;collection:string;selected:string;disabled:boolean;canChoose:(id:string)=>boolean;onChoose:(id:string)=>void;budget:number|null;room:View|null;children?:ReactNode}){
 const [query,setQuery]=useState(''),[onlyStars,setOnlyStars]=useState(false),[favorites,setFavorites]=useState<string[]>([]);
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('acai-favorites')||'[]');if(Array.isArray(v))setFavorites(v.filter(id=>INGREDIENTS.some(i=>i.id===id)));}catch{}},[]);
 const favorite=(id:string)=>setFavorites(prev=>{const next=prev.includes(id)?prev.filter(v=>v!==id):[...prev,id];try{localStorage.setItem('acai-favorites',JSON.stringify(next))}catch{}return next});
 const q=query.trim().toLowerCase(),visible=INGREDIENTS.filter(i=>(q||onlyStars||i.category===category)&&(collection==='all'||collection==='fantasy'&&!!FANTASY_BY_ID[i.id]||collection==='classic'&&!FANTASY_BY_ID[i.id])&&(!onlyStars||favorites.includes(i.id))&&(!q||`${i.name} ${i.category} ${FANTASY_BY_ID[i.id]?.description||''}`.toLowerCase().includes(q))),current=INGREDIENTS.find(i=>i.id===selected);
 return <section className="ingredient-browser" aria-label="Browse ingredients"><div className="ingredient-search"><div><Search size={17}/><Input aria-label="Search ingredients" placeholder="Find fruit, crunch, drizzle…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Button aria-pressed={onlyStars} onClick={()=>setOnlyStars(!onlyStars)}><Star size={16}/>Favorites</Button></div>{current&&<div className={`ingredient-feature ${!canChoose(current.id)?'unavailable':''}`}><div className="ingredient-large-preview"><Picture id={current.id}/></div><div><span className="eyebrow">{current.category}{FANTASY_BY_ID[current.id]?' · FANTASY':''}</span><h3>{current.name}</h3><p>{FANTASY_BY_ID[current.id]?.description||'Choose an arrangement, then tap your bowl to place it.'}</p><span className="ingredient-state">{!canChoose(current.id)?<><Lock size={13}/>Unavailable this round</>:<><Check size={13}/>Selected{budget!==null?` · ${current.price} coins per piece`:''}</>}</span></div></div>}<p className="browser-count" role="status">{visible.length} {visible.length===1?'ingredient':'ingredients'}{q||onlyStars?' across categories':` in ${category.toLowerCase()}`}</p><div className="ingredient-grid">{!q&&!onlyStars&&children}{visible.map(i=>{const available=canChoose(i.id),owner=room?.mutation?.id==='exclusive'?room.claims[i.id]:null;return <div className={`ingredient-choice ${selected===i.id?'is-selected':''} ${!available?'is-unavailable':''}`} key={i.id}><Button className="ingredient-tile" aria-pressed={selected===i.id} disabled={disabled||!available} title={available?i.name:'Unavailable under this round’s mutation'} onClick={()=>onChoose(i.id)}><Picture id={i.id}/><span className="ingredient-name">{i.name}</span>{FANTASY_BY_ID[i.id]&&<small className="fantasy-label">FANTASY</small>}{owner&&<span className="ingredient-owner">{owner===room?.me?'Claimed by you':`Claimed by ${room?.players.find(p=>p.id===owner)?.name||'another chef'}`}</span>}{budget!==null&&<span className="ingredient-price">{i.price} coins / piece</span>}{selected===i.id&&<Check className="selected-check" size={14}/>}</Button><Button className="ingredient-favorite" aria-label={`${favorites.includes(i.id)?'Remove':'Add'} ${i.name} ${favorites.includes(i.id)?'from':'to'} favorites`} aria-pressed={favorites.includes(i.id)} onClick={()=>favorite(i.id)}><Star size={14} fill={favorites.includes(i.id)?'currentColor':'none'}/></Button></div>})}</div>{!visible.length&&<div className="ingredient-empty"><strong>{onlyStars?'No favorites match yet.':'No ingredients found.'}</strong><p>{onlyStars?'Tap a star on an ingredient to save it here.':'Try a shorter name or switch your ingredient collection.'}</p>{(q||onlyStars)&&<Button onClick={()=>{setQuery('');setOnlyStars(false)}}>Clear filters</Button>}</div>}</section>
}
export function CountertopPicker({value,disabled,onChange}:{value:string;disabled:boolean;onChange:(value:string)=>void}){return <div className="countertop-picker"><span className="field-label">Your café counter</span><div aria-label="Countertop styles">{[['studio','Berry café'],['oak','Honey oak'],['terrazzo','Confetti stone'],['berry','Berry glaze']].map(([id,name])=><Button disabled={disabled} key={id} aria-pressed={value===id} onClick={()=>onChange(id)}><i className={`counter-swatch swatch-${id}`}/>{name}</Button>)}</div><span className="hint">Just the scenery — your recipe stays the same.</span></div>}
