"use client";
import {useCallback,useEffect,useState} from 'react';
import {Crown,Trophy,RefreshCw,X,Medal} from 'lucide-react';
import {Button} from '@/components/ui/button';
type Entry={rank:number;position:number;name:string;wins:number;games:number;mine:number};
export function Leaderboard({refreshKey,onClose}:{refreshKey:string;onClose:()=>void}){
 const [rows,setRows]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const r=await fetch('/api/game?leaderboard=1',{signal,cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load the leaderboard.');if(!signal?.aborted){setRows(data.entries);setError('');}}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Could not load the leaderboard.');}finally{if(!signal?.aborted)setLoading(false);}},[]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);const timer=setInterval(()=>{if(!document.hidden)void load(controller.signal)},30000);return()=>{controller.abort();clearInterval(timer)}},[load,refreshKey]);
 const top=rows.filter(r=>r.position<=50),mine=rows.find(r=>r.mine);
 return <section className="champion-board" aria-labelledby="champion-title"><div className="champion-heading"><div><p className="eyebrow"><Crown size={15}/> THE HALL OF FLAVOR</p><h1 id="champion-title">The sweetest victories.</h1><p>Big ideas. Beautiful bowls. A place among the champions.</p></div><div className="champion-buttons"><Button aria-label="Refresh leaderboard" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/></Button><Button aria-label="Close leaderboard" onClick={onClose}><X size={18}/></Button></div></div>
 <div className="champion-rules"><span><Trophy size={16}/> Ranked by total match wins</span><span>All time · shared wins count</span></div>
 {error?<div className="champion-empty" role="alert"><p>{error}</p><Button onClick={()=>void load()}>Try again</Button></div>:loading&&!rows.length?<div className="champion-empty" role="status">Setting the champions’ table…</div>:!rows.length?<div className="champion-empty"><Trophy size={40}/><h2>The first crown is waiting.</h2><p>Finish a three-round multiplayer match to earn a spot.<br/>Win tracking starts with this update. Solo practice does not count.</p></div>:<><div className="champion-podium">{top.slice(0,3).map((r,i)=><article className={`podium-chef podium-${i} ${r.mine?'is-you':''}`} key={i}><span className="podium-rank">{r.rank===1?<Crown size={21}/>:<Medal size={21}/>}#{r.rank}</span><div className="podium-avatar">{r.name.slice(0,1).toUpperCase()}</div><h2>{r.name}{!!r.mine&&<small>YOU</small>}</h2><strong>{r.wins}<span>{r.wins===1?'win':'wins'}</span></strong><p>{r.games} {r.games===1?'game':'games'} played</p></article>)}</div>
 <div className="champion-table"><div className="champion-row champion-columns"><span>RANK / CHEF</span><span>WINS</span><span>GAMES</span><span>WIN RATE</span></div>{top.map((r,i)=><div className={`champion-row ${r.mine?'is-you':''}`} key={i}><div><span className="champion-number">{r.rank===1?<Crown size={17}/>:r.rank}</span><strong>{r.name}{!!r.mine&&<small>YOU</small>}</strong></div><strong className="champion-wins">{r.wins}</strong><span>{r.games}</span><span>{Math.round(r.wins/r.games*100)}%</span></div>)}</div>
 <div className="your-standing"><Trophy size={23}/><div><strong>{mine?`Your standing: #${mine.rank}`:'Your next bowl could make history.'}</strong><span>{mine?`${mine.wins} wins · ${mine.games} completed games`:'Finish a multiplayer match to join the leaderboard.'}</span></div></div></>}
 <p className="champion-footnote">A win means the highest total after all three rounds. Ties share the crown. Records follow this browser; the same name on another device is a separate chef. Clearing cookies resets your connection to your record.</p>
 </section>;
}
