"use client";
import {PackageOpen,Palette,Hand,FlipVertical2,LockKeyhole,Sparkles,Check,Lock} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {MUTATIONS,COLORS,INGREDIENTS,colorScore,pickedTypes,type Mutation,type Bowl,type View} from '@/lib/game';
const icons={mystery:PackageOpen,color:Palette,slots:Hand,gravity:FlipVertical2,exclusive:LockKeyhole};
export function MutationPanel({mutation,bowl,room,onStage,disabled=false,revealed=false}:{mutation:Mutation|null;bowl:Bowl;room:View|null;onStage:(stage:'toppings')=>void;disabled?:boolean;revealed?:boolean}){
 if(!mutation)return null;const info=MUTATIONS.find(m=>m.id===mutation.id)!,Icon=icons[mutation.id],color=COLORS.find(c=>c.id===mutation.color),score=colorScore(bowl,mutation.color||'pink');
 return <section className={`mutation-panel mutation-${mutation.id}`} aria-label={`${info.name} mutation`}><div className="mutation-heading"><span className="mutation-icon"><Icon size={29}/></span><div><span className="mutation-eyebrow"><Sparkles size={13}/>ROUND MUTATION</span><h2>{mutation.id==='color'?`${color?.name||'Pink'} Round`:info.name}</h2><span>{info.tag}</span></div><span className="mutation-stamp">SURPRISE!</span></div><p>{info.description}</p>
 {mutation.id==='color'&&<div className="color-challenge"><div><span style={{background:color?.hex}} className="color-dot"/><strong>{score}% {color?.name?.toLowerCase()||'pink'}</strong><span>{score>=55?<><Check size={15}/>Bonus unlocked</>:'55% unlocks +1 point'}</span></div><div className="color-track" role="meter" aria-label="Dominant color score" aria-valuenow={score} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${score}%`,background:color?.hex}}/><i/></div><small>Rough color estimate from your base, toppings, and their size. Players still judge the best bowl.</small></div>}
 {mutation.id==='slots'&&<div className="pick-counter">{[1,2,3].map(n=><span className={n<=pickedTypes(bowl)?'pick-used':''} key={n}>{n===1?'Base':`Pick ${n}`}{n<=pickedTypes(bowl)&&<Check size={15}/>}</span>)}<strong>{pickedTypes(bowl)}/3 types</strong></div>}
 {mutation.id==='gravity'&&<><div className="gravity-steps">{['pour','toppings','sealed'].map((stage,i)=><span className={bowl.gravity===stage?'gravity-current':''} key={stage}>{i+1}. {['Drizzle first','Toppings next','Base last'][i]}</span>)}</div>{bowl.gravity==='pour'?<Button className="mutation-button" disabled={disabled||!bowl.pieces.length} onClick={()=>onStage('toppings')}>Done pouring · add toppings</Button>:bowl.gravity==='toppings'?<p className="gravity-tip">When you’re happy with the toppings, choose a base to seal your upside-down masterpiece.</p>:<p className="gravity-tip"><Lock size={15}/>Sealed! Your base sits over your toppings. Give your bowl a name and finish.</p>}</>}
 {mutation.id==='mystery'&&<div className="mystery-tip"><PackageOpen size={18}/>{(room?.myMystery?.revealed||revealed)?'Revealed and locked in. Keep building around your surprise.':'Choose the ? tile, then tap your bowl. One piece. No take-backs.'}</div>}
 {mutation.id==='exclusive'&&<div className="claim-board"><strong>Ingredient rush</strong><div>{Object.entries(room?.claims||{}).length?Object.entries(room?.claims||{}).map(([id,owner])=><span key={id} className={owner===room?.me?'claim-yours':''}><Lock size={12}/>{INGREDIENTS.find(i=>i.id===id)?.name}<small>{owner===room?.me?'Yours':room?.players.find(p=>p.id===owner)?.name||'Claimed'}</small></span>):<p>Everything is up for grabs. Your first placement claims an ingredient.</p>}</div></div>}
 </section>
}
export function MutationGuide(){return <section className="mutation-guide"><div><p className="eyebrow">EXPECT THE UNEXPECTED</p><h2>The bowl lab is open.</h2><p>Random rounds get a surprise twist. Discover the rule when the round starts, then make it delicious.</p></div><div className="mutation-pills">{MUTATIONS.map(m=>{const Icon=icons[m.id];return <span key={m.id}><Icon size={17}/>{m.name}</span>})}</div></section>}
