"use client";
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {INGREDIENTS,type Bowl,type Piece} from '@/lib/game';
import {ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Trash2,Copy,Layers} from 'lucide-react';
export function PieceEditor({bowl,index,onSelect,onChange,disabled}:{bowl:Bowl;index:number;onSelect:(n:number)=>void;onChange:(b:Bowl)=>void;disabled:boolean}){
 const piece=bowl.pieces[index];
 const edit=(patch:Partial<Piece>)=>{if(disabled||!piece)return;const updated={...piece,...patch};const d=Math.hypot(updated.x-50,updated.y-50);if(d>36){updated.x=50+(updated.x-50)*36/d;updated.y=50+(updated.y-50)*36/d;}onChange({...bowl,pieces:bowl.pieces.map((p,i)=>i===index?updated:p)});};
 return <section className="piece-editor"><div className="panel-heading"><h3>Fine-tune your bowl</h3><span>Drag to move</span></div><Select value={piece?String(index):''} onValueChange={v=>onSelect(Number(v))} disabled={disabled||!bowl.pieces.length}><SelectTrigger aria-label="Select a topping to edit" className="piece-picker"><SelectValue placeholder="Choose a topping"/></SelectTrigger><SelectContent>{bowl.pieces.map((p,i)=><SelectItem key={p.uid||i} value={String(i)}>{i+1}. {INGREDIENTS.find(t=>t.id===p.id)?.name}</SelectItem>)}</SelectContent></Select>{piece?<><div className="tweak-line"><label id="selected-size">Size · {Math.round(piece.size)}</label><Slider aria-labelledby="selected-size" min={6} max={40} value={[piece.size]} disabled={disabled} onValueChange={v=>edit({size:v[0]})}/></div><div className="tweak-line"><label id="selected-rotation">Rotation · {Math.round(piece.rotation)}°</label><Slider aria-labelledby="selected-rotation" min={-180} max={180} value={[piece.rotation>180?piece.rotation-360:piece.rotation]} disabled={disabled} onValueChange={v=>edit({rotation:v[0]})}/></div><div className="nudge-tools"><span>Move</span>{[[-2,0,'Left',ArrowLeft],[0,-2,'Up',ArrowUp],[0,2,'Down',ArrowDown],[2,0,'Right',ArrowRight]].map(([dx,dy,label,Icon]:any)=><Button key={label} aria-label={`Move topping ${String(label).toLowerCase()}`} disabled={disabled} onClick={()=>edit({x:piece.x+dx,y:piece.y+dy})}><Icon size={16}/></Button>)}</div><div className="piece-actions"><Button disabled={disabled||bowl.pieces.length>=64} onClick={()=>{onChange({...bowl,pieces:[...bowl.pieces,{...piece,uid:crypto.randomUUID(),x:piece.x*.95+2.5,y:piece.y*.95+2.5}]});onSelect(bowl.pieces.length)}}><Copy size={15}/>Duplicate</Button><Button disabled={disabled||index===bowl.pieces.length-1} onClick={()=>{onChange({...bowl,pieces:[...bowl.pieces.filter((_,i)=>i!==index),piece]});onSelect(bowl.pieces.length-1)}}><Layers size={15}/>Bring forward</Button><Button disabled={disabled} onClick={()=>{onChange({...bowl,pieces:bowl.pieces.filter((_,i)=>i!==index)});onSelect(Math.max(-1,index-1))}}><Trash2 size={15}/>Remove</Button></div></>:<p className="hint">Select a topping on your bowl or from this list. Then drag it, resize it, or adjust its angle.</p>}</section>
}
