"use client";
import {useEffect,useState} from 'react';
import {Globe,Lock,Users,Timer,RefreshCw} from 'lucide-react';
import {Button} from './ui/button';
type Visibility='public'|'private';
type ListedRoom={code:string;name:string;players:number;online:number;maxPlayers:number;roundSeconds:number;visibility:Visibility;mine:boolean};
export function RoomPrivacy({value,disabled,onChange,lobby=false}:{value:Visibility;disabled:boolean;onChange:(v:Visibility)=>void;lobby?:boolean}){return <section className={`room-privacy ${lobby?'lobby-privacy':''}`} aria-label="Room privacy"><strong>{lobby?'Who can join your table?':'Room privacy'}</strong><div><Button aria-pressed={value==='private'} disabled={disabled} onClick={()=>onChange('private')}><Lock size={16}/>Private</Button><Button aria-pressed={value==='public'} disabled={disabled} onClick={()=>onChange('public')}><Globe size={16}/>Public</Button></div><p>{value==='public'?'Listed in Find a table. Anyone can join while the lobby is open.':'Invite only. Friends join with your room code or invite link.'}</p></section>}
export function RoomBrowser({name,busy,onJoin}:{name:string;busy:boolean;onJoin:(code:string)=>Promise<unknown>}){
 const [scope,setScope]=useState<'public'|'private'>('public'),[rooms,setRooms]=useState<ListedRoom[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();let pending=false;setRooms([]);setLoading(true);setError('');const read=async()=>{if(pending||document.hidden)return;pending=true;setRefreshing(true);try{const response=await fetch(`/api/game?rooms=1&scope=${scope}`,{signal:controller.signal,cache:'no-store'});const data=await response.json() as {rooms?:ListedRoom[];error?:string};if(!response.ok)throw Error(data.error||'Could not load rooms.');if(!controller.signal.aborted){setRooms(data.rooms||[]);setError('');}}catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:'Could not load rooms.');setRooms([]);}}finally{pending=false;if(!controller.signal.aborted){setLoading(false);setRefreshing(false);}}};void read();const interval=setInterval(()=>void read(),8000);const visible=()=>{if(!document.hidden)void read()};document.addEventListener('visibilitychange',visible);return()=>{controller.abort();clearInterval(interval);document.removeEventListener('visibilitychange',visible)}},[scope,refresh]);
 return <section className="room-browser" aria-labelledby="room-browser-title"><header><div><p className="eyebrow">THERE'S ROOM AT THE TABLE</p><h2 id="room-browser-title">Find a table</h2><p>Join a friendly competition, or invite friends to your own.</p></div><Button disabled={refreshing||busy} onClick={()=>setRefresh(v=>v+1)} aria-label="Refresh room list"><RefreshCw size={16} className={refreshing?'room-refreshing':''}/>Refresh</Button></header><div className="room-browser-tabs" aria-label="Room list"><Button aria-pressed={scope==='public'} onClick={()=>setScope('public')}><Globe size={16}/>Public rooms</Button><Button aria-pressed={scope==='private'} onClick={()=>setScope('private')}><Lock size={16}/>My private rooms</Button></div><p className="room-browser-hint">{scope==='private'?'Only your private lobbies appear here. To join a friend’s private room, enter their code above.':'Open public lobbies update automatically. Games already in progress stay off this list.'}{!name.trim()?' Enter your chef name above to join.':''}</p><div role="status" aria-live="polite">{loading?<p className="room-empty">Finding open tables…</p>:error?<p className="room-empty room-list-error">{error} Use Refresh to try again.</p>:!rooms.length?<div className="room-empty"><strong>{scope==='public'?'No public tables open yet.':'No private lobbies of your own yet.'}</strong><p>{scope==='public'?'Be the host! Choose Public above and create a room.':'Create a Private room above and share its invite with friends.'}</p></div>:null}</div><div className="room-list">{rooms.map(room=><article className="room-list-card" key={room.code}><div className="room-list-heading"><span className="room-host-avatar" aria-hidden="true">{room.name.slice(0,1).toUpperCase()}</span><div><h3>{room.name}’s table</h3><span>{room.visibility==='public'?'Public lobby':'Private lobby'}{room.mine?' · your table':''}</span></div></div><div className="room-list-facts"><span><Users size={16}/>{room.players}/{room.maxPlayers} chefs</span><span><Timer size={16}/>{Math.floor(room.roundSeconds/60)}:{String(room.roundSeconds%60).padStart(2,'0')} builds</span></div><footer><span>{room.online?`${room.online} connected`:'Waiting for you'}</span><Button className="primary" disabled={busy||!name.trim()} onClick={()=>void onJoin(room.code)}>{room.mine?'Rejoin room':'Join room'}</Button></footer></article>)}</div></section>
}
