"use client";
import {useEffect,useRef,useState} from 'react';
import {useSettings} from './settings';
import {Coins,Heart,Sparkles,Palmtree,IceCreamBowl,Coffee,Crown,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AWARDS,THEMES,ROUND_BUDGET,bowlCost,type Bowl,type View,type AwardId} from '@/lib/game';
const icons=[Palmtree,Sparkles,Coffee,Heart,IceCreamBowl];
export function ThemeCard({theme,round,budget=false,children}:{theme:typeof THEMES[number];round?:number;budget?:boolean;children?:React.ReactNode}){
 const Icon=theme.name==='Beach day'?Palmtree:theme.name==='Dessert monster'?IceCreamBowl:theme.name==='Fancy café'?Coffee:icons[theme.id%icons.length];
 return <article className={`theme-card theme-tone-${theme.id%5}`}><div className="theme-card-top"><span>{round?`ROUND ${round}`:'YOUR CHALLENGE'}</span><Icon size={27}/></div><h3>{theme.name}</h3><p>{theme.description}</p><span className={`theme-rule ${budget?'budget-rule':''}`}>{budget?<><Coins size={15}/>{ROUND_BUDGET}-coin budget</>:<><Sparkles size={15}/>Free creation</>}</span>{children}</article>
}
export function ThemeDeck({room,busy,onChange}:{room:View;busy:boolean;onChange:(themes:number[])=>void}){return <section className="theme-deck"><div className="deck-heading"><div><p className="eyebrow">THE MENU FOR TONIGHT</p><h2>Three rounds. Three little worlds.</h2></div><span>{room.host===room.me?'Pick your themes below.':'Your host chooses the theme cards.'}</span></div><div className="theme-cards">{room.themes.map((id,i)=><ThemeCard key={i} theme={id===-1?{id:0,name:'Surprise theme',description:'A fresh theme is revealed when this round begins.'}:THEMES[id]} round={i+1} budget={room.modes[i]==='budget'}>{room.host===room.me&&<Select value={String(id)} disabled={busy} onValueChange={v=>onChange(room.themes.map((t,j)=>i===j?Number(v):t))}><SelectTrigger aria-label={`Round ${i+1} theme`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="-1">Random theme</SelectItem>{THEMES.map(t=><SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>)}</SelectContent></Select>}</ThemeCard>)}</div><p className="deck-note">{room.roundSeconds} seconds · 30-second voting · {room.audienceAwards?'Best bowl + two audience awards':'Vote for the best bowl'}{room.budgetRound>0?' · Bases are on the house':''}</p></section>}
export function BudgetMeter({bowl,budget}:{bowl:Bowl;budget:number}){
 const {preferences}=useSettings(),spent=bowlCost(bowl),left=Math.max(0,budget-spent);
 const [display,setDisplay]=useState(left),[pulse,setPulse]=useState<{id:number;delta:number}|null>(null);
 const shown=useRef(left),previous=useRef({spent,budget}),sequence=useRef(0);
 useEffect(()=>{const prior=previous.current;previous.current={spent,budget};const delta=spent-prior.spent;
  if(prior.budget!==budget){shown.current=left;setDisplay(left);setPulse(null);return;}
  if(delta)setPulse({id:++sequence.current,delta});
  if(!preferences.motion){shown.current=left;setDisplay(left);return;}
  const from=shown.current,start=performance.now();let frame=0;
  const tick=(now:number)=>{const t=Math.min(1,(now-start)/520),ease=1-Math.pow(1-t,3);shown.current=from+(left-from)*ease;setDisplay(shown.current);if(t<1)frame=requestAnimationFrame(tick);else shown.current=left;};
  frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
 },[spent,left,budget,preferences.motion]);
 useEffect(()=>{if(!pulse)return;const timer=setTimeout(()=>setPulse(null),1100);return()=>clearTimeout(timer)},[pulse]);
 return <section className={`budget-meter ${left<10?'budget-low':''} ${preferences.motion?'budget-animated':''}`} aria-label="Round budget"><div><span key={pulse?.id||0} className={`budget-symbol ${pulse?pulse.delta>0?'coin-spending':'coin-refunding':''}`} aria-hidden="true"><Coins size={24}/>{pulse&&preferences.motion&&<span className="coin-particles">{[0,1,2].map(i=><Coins key={i} size={15} style={{'--coin-index':i} as React.CSSProperties}/>)}</span>}</span><div className="budget-count"><strong><span className="coin-total">{Math.round(display)}</span> <small>coins left</small></strong><p>{budget-Math.round(display)} of {budget} spent · bases included</p>{pulse&&<span key={pulse.id} className={`coin-change ${pulse.delta>0?'coin-used':'coin-refund'}`} aria-hidden="true">{pulse.delta>0?'−':'+'}{Math.abs(pulse.delta)} {pulse.delta>0?'spent':'refunded'}</span>}</div><span className="budget-label">BUDGET ROUND</span></div><div role="meter" aria-label="Coins remaining" aria-valuemin={0} aria-valuemax={budget} aria-valuenow={left} className="budget-track"><span style={{width:`${budget?display/budget*100:0}%`}}/></div><p className="budget-tip">Each placed piece has a price. Removing or undoing pieces gives coins back.</p><span className="sr-only" role="status">{pulse?`${Math.abs(pulse.delta)} coins ${pulse.delta>0?'spent':'refunded'}. ${left} coins remaining.`:''}</span></section>
}
export function AwardVoting({room,entry,busy,closed,onVote}:{room:View;entry:View['entries'][number];busy:boolean;closed:boolean;onVote:(award:AwardId,ballot:string)=>void}){if(!room.audienceAwards)return null;return <div className="award-voting"><span>Audience awards</span>{AWARDS.map(a=>{const voted=room.myAwardVotes[a.id],Icon=a.id==='creative'?Sparkles:Heart;return <Button key={a.id} className={`award-vote award-${a.id} ${voted===entry.ballot?'award-chosen':''}`} disabled={busy||closed||entry.mine||!!voted} onClick={()=>onVote(a.id,entry.ballot)} aria-label={`${a.name} for ${entry.bowl.title||'this bowl'}`}><Icon size={17}/>{a.name}{voted===entry.ballot&&<Check size={15}/>}</Button>})}</div>}
export function AudienceResults({room}:{room:View}){if(!room.audienceAwards)return null;return <section className="audience-results"><div className="deck-heading"><div><p className="eyebrow">THE TABLE HAS SPOKEN</p><h2>Audience favorites</h2></div><span>This round’s awards · separate from points</span></div><div className="audience-awards">{AWARDS.map(a=>{const max=Math.max(0,...room.entries.map(e=>e.awards?.[a.id]||0));const winners=room.entries.filter(e=>max>0&&e.awards?.[a.id]===max),Icon=a.id==='creative'?Sparkles:Heart;return <article className={`audience-award award-${a.id}`} key={a.id}><span className="award-medallion"><Icon size={25}/></span><div><h3>{a.name}</h3><strong>{winners.length?winners.map(w=>w.name).join(' & '):'No votes this round'}</strong><p>{max>0?`${max} ${max===1?'vote':'votes'}${winners.length>1?' each · shared award':''}`:a.description}</p></div>{winners.some(w=>w.mine)&&<span className="your-award"><Crown size={14}/>You won!</span>}</article>})}</div></section>}
