"use client";
import {Coins,Heart,Sparkles,Palmtree,IceCreamBowl,Coffee,Crown,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AWARDS,THEMES,ROUND_BUDGET,bowlCost,type Bowl,type View,type AwardId} from '@/lib/game';
const icons=[Palmtree,Sparkles,Coffee,Heart,IceCreamBowl];
export function ThemeCard({theme,round,budget=false,children}:{theme:typeof THEMES[number];round?:number;budget?:boolean;children?:React.ReactNode}){
 const Icon=theme.name==='Beach day'?Palmtree:theme.name==='Dessert monster'?IceCreamBowl:theme.name==='Fancy café'?Coffee:icons[theme.id%icons.length];
 return <article className={`theme-card theme-tone-${theme.id%5}`}><div className="theme-card-top"><span>{round?`ROUND ${round}`:'YOUR CHALLENGE'}</span><Icon size={27}/></div><h3>{theme.name}</h3><p>{theme.description}</p><span className={`theme-rule ${budget?'budget-rule':''}`}>{budget?<><Coins size={15}/>{ROUND_BUDGET}-coin budget</>:<><Sparkles size={15}/>Free creation</>}</span>{children}</article>
}
export function ThemeDeck({room,busy,onChange}:{room:View;busy:boolean;onChange:(themes:number[])=>void}){return <section className="theme-deck"><div className="deck-heading"><div><p className="eyebrow">THE MENU FOR TONIGHT</p><h2>Three rounds. Three little worlds.</h2></div><span>{room.host===room.me?'Pick your themes below.':'Your host chooses the theme cards.'}</span></div><div className="theme-cards">{room.themes.map((id,i)=><ThemeCard key={i} theme={THEMES[id]} round={i+1} budget={room.budgetRound===i+1}>{room.host===room.me&&<Select value={String(id)} disabled={busy} onValueChange={v=>onChange(room.themes.map((t,j)=>i===j?Number(v):t))}><SelectTrigger aria-label={`Round ${i+1} theme`}><SelectValue/></SelectTrigger><SelectContent>{THEMES.map(t=><SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>)}</SelectContent></Select>}</ThemeCard>)}</div><p className="deck-note">105 seconds per round · {room.audienceAwards?'Best bowl + two audience awards':'Vote for the best bowl'}{room.budgetRound>0?' · Bases are on the house':''}</p></section>}
export function BudgetMeter({bowl,budget}:{bowl:Bowl;budget:number}){const spent=bowlCost(bowl),left=budget-spent;return <section className={`budget-meter ${left<10?'budget-low':''}`} aria-label="Round budget"><div><span className="budget-symbol"><Coins size={24}/></span><div><strong>{left} <small>coins left</small></strong><p>{spent} of {budget} spent · bases included</p></div><span className="budget-label">BUDGET ROUND</span></div><div role="meter" aria-label="Coins remaining" aria-valuemin={0} aria-valuemax={budget} aria-valuenow={Math.max(0,left)} className="budget-track"><span style={{width:`${Math.max(0,left)/budget*100}%`}}/></div><p className="budget-tip">Each placed piece has a price. Removing or undoing pieces gives coins back.</p></section>}
export function AwardVoting({room,entry,busy,closed,onVote}:{room:View;entry:View['entries'][number];busy:boolean;closed:boolean;onVote:(award:AwardId,ballot:string)=>void}){if(!room.audienceAwards)return null;return <div className="award-voting"><span>Audience awards</span>{AWARDS.map(a=>{const voted=room.myAwardVotes[a.id],Icon=a.id==='creative'?Sparkles:Heart;return <Button key={a.id} className={`award-vote award-${a.id} ${voted===entry.ballot?'award-chosen':''}`} disabled={busy||closed||entry.mine||!!voted} onClick={()=>onVote(a.id,entry.ballot)} aria-label={`${a.name} for ${entry.bowl.title||'this bowl'}`}><Icon size={17}/>{a.name}{voted===entry.ballot&&<Check size={15}/>}</Button>})}</div>}
export function AudienceResults({room}:{room:View}){if(!room.audienceAwards)return null;return <section className="audience-results"><div className="deck-heading"><div><p className="eyebrow">THE TABLE HAS SPOKEN</p><h2>Audience favorites</h2></div><span>This round’s awards · separate from points</span></div><div className="audience-awards">{AWARDS.map(a=>{const max=Math.max(0,...room.entries.map(e=>e.awards?.[a.id]||0));const winners=room.entries.filter(e=>max>0&&e.awards?.[a.id]===max),Icon=a.id==='creative'?Sparkles:Heart;return <article className={`audience-award award-${a.id}`} key={a.id}><span className="award-medallion"><Icon size={25}/></span><div><h3>{a.name}</h3><strong>{winners.length?winners.map(w=>w.name).join(' & '):'No votes this round'}</strong><p>{max>0?`${max} ${max===1?'vote':'votes'}${winners.length>1?' each · shared award':''}`:a.description}</p></div>{winners.some(w=>w.mine)&&<span className="your-award"><Crown size={14}/>You won!</span>}</article>})}</div></section>}
