"use client";
import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {Settings as SettingsIcon} from 'lucide-react';
import {Button} from './ui/button';
import {Switch} from './ui/switch';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from './ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from './ui/select';
type Preferences={theme:'light'|'dark'|'system';motion:boolean;rotate:boolean;hints:boolean};
const defaults:Preferences={theme:'system',motion:true,rotate:true,hints:true};
const Context=createContext({preferences:defaults,update:(_patch:Partial<Preferences>)=>{}});
export const useSettings=()=>useContext(Context);
export function SettingsProvider({children}:{children:ReactNode}){
const [preferences,setPreferences]=useState(defaults),[loaded,setLoaded]=useState(false);
useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('acai-settings')||'{}');setPreferences({theme:['light','dark','system'].includes(p.theme)?p.theme:'system',motion:typeof p.motion==='boolean'?p.motion:true,rotate:typeof p.rotate==='boolean'?p.rotate:true,hints:typeof p.hints==='boolean'?p.hints:true});}catch{}setLoaded(true)},[]);
useEffect(()=>{if(!loaded)return;const media=matchMedia('(prefers-color-scheme: dark)'),motion=matchMedia('(prefers-reduced-motion: reduce)');const apply=()=>{document.documentElement.dataset.theme=preferences.theme==='system'?(media.matches?'dark':'light'):preferences.theme;document.documentElement.dataset.motion=!preferences.motion||motion.matches?'reduced':'full';document.documentElement.dataset.hints=preferences.hints?'show':'hide';};apply();media.addEventListener('change',apply);motion.addEventListener('change',apply);try{localStorage.setItem('acai-settings',JSON.stringify(preferences))}catch{}return()=>{media.removeEventListener('change',apply);motion.removeEventListener('change',apply)}},[preferences,loaded]);
return <Context.Provider value={{preferences,update:patch=>setPreferences(p=>({...p,...patch}))}}>{children}</Context.Provider>;
}
export function SettingsButton(){const {preferences:p,update}=useSettings();return <Dialog><DialogTrigger asChild><Button className="settings-button"><SettingsIcon size={17}/>Settings</Button></DialogTrigger><DialogContent className="settings-dialog"><DialogTitle>Make yourself at home</DialogTitle><DialogDescription>Display preferences are saved on this browser.</DialogDescription><div className="settings-row"><div><strong>Appearance</strong><span>Choose your studio lighting.</span></div><Select value={p.theme} onValueChange={v=>update({theme:v as Preferences['theme']})}><SelectTrigger aria-label="Appearance"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="system">Use device setting</SelectItem><SelectItem value="light">Light</SelectItem><SelectItem value="dark">Dark</SelectItem></SelectContent></Select></div>{([{key:'motion',title:'Animations',text:'Ingredient drops and celebration effects.'},{key:'rotate',title:'Showcase rotation',text:'Let displayed bowls rotate automatically.'},{key:'hints',title:'Bowl control hints',text:'Show placement and camera tips below bowls.'}] as const).map(o=><div className="settings-row" key={o.key}><div><strong id={`setting-${o.key}`}>{o.title}</strong><span id={`setting-${o.key}-description`}>{o.text}</span></div><Switch aria-labelledby={`setting-${o.key}`} aria-describedby={`setting-${o.key}-description`} checked={p[o.key]} onCheckedChange={checked=>update({[o.key]:checked})}/></div>)}<p className="settings-note">Your device’s reduced-motion preference is respected. Game timers and multiplayer rules stay the same for everyone.</p><Button onClick={()=>update(defaults)}>Restore defaults</Button></DialogContent></Dialog>}
