"use client";
import {useEffect,useRef,useState} from 'react';
import {Check,ChefHat,Sparkles,Lock,Scissors,Utensils,Trophy} from 'lucide-react';
import {Button} from './ui/button';
import {Bowl} from './bowl';
import {RevealReactions} from './engagement';
import {ORDERS,TWISTS,orderProgress,twistProgress,ACHIEVEMENTS} from '@/lib/studio';
import type {Bowl as BowlData,View} from '@/lib/game';
export function CustomerCard({bowl,order,twist,until}:{bowl:BowlData;order:string|null;twist:string|null;until:number}){
 const o=ORDERS.find(v=>v.id===order),t=TWISTS.find(v=>v.id===twist),progress=orderProgress(bowl,order||'');return <div className="customer-grid">{o&&<section className="customer-ticket"><div className="ticket-top"><ChefHat/><span>ORDER FOR {o.customer.toUpperCase()}</span><small>UP TO +4</small></div><h2>{o.title}</h2><p>One point per request. Perfect order earns one extra.</p><ul>{o.requests.map((r,i)=><li className={progress[i]?'request-done':''} key={r}><span>{progress[i]?<Check size={14}/>:i+1}</span>{r}</li>)}</ul></section>}<section className={`twist-ticket ${t?'twist-open':''}`}><Sparkles/><p className="eyebrow">{t?'THE MID-ROUND TWIST · +2':'SOMETHING DELICIOUS IS COMING'}</p><h2>{t?t.name:`A surprise in ${Math.max(0,Math.ceil(until))}s`}</h2><p>{t?t.description:'Keep a little space in your bowl. A new challenge arrives halfway through.'}</p>{t&&<strong>{twistProgress(bowl,t.id)?'✓ Bonus ready · keep it in your final bowl':'Make the adjustment to earn +2 points.'}</strong>}</section></div>;
}
export function FruitPrep({id,prepared,disabled,onCut}:{id:string;prepared:boolean;disabled:boolean;onCut:()=>void}){const start=useRef<{x:number;y:number}|null>(null),[cut,setCut]=useState(false);useEffect(()=>setCut(false),[id]);if(!['strawberry','kiwi','banana'].includes(id))return null;const slice=()=>{if(disabled)return;setCut(true);onCut()};return <section className="prep-board"><div><p className="eyebrow"><Scissors size={14}/> THE PREP COUNTER</p><h3>{prepared?'Freshly sliced. Ready to plate.':'A little hands-on preparation.'}</h3><p>Swipe across the fruit to slice it. Quick placement is always available.</p></div><div className={`prep-fruit ${cut||prepared?'fruit-cut':''} fruit-${id}`} onPointerDown={e=>{if(disabled)return;start.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(start.current&&Math.hypot(e.clientX-start.current.x,e.clientY-start.current.y)>45){start.current=null;slice()}}} onPointerUp={()=>{start.current=null}} onPointerCancel={()=>{start.current=null}} aria-hidden="true"><span/><span/><span/><i/></div><Button disabled={disabled||prepared} onClick={slice}><Scissors size={15}/>{prepared?'Sliced ✓':'Slice fruit'}</Button></section>}
export function CinematicReveal({room,now,onReact}:{room:View;now:number;onReact:(ballot:string,kind:string)=>void}){const entries=room.entries;if(!entries.length)return null;const index=Math.floor(Math.max(0,(now-(room.deadline-90000)))/8000)%entries.length,entry=entries[index];return <section className="cinematic-stage" key={entry.ballot}><div className="reveal-orbit"/><div className="cinematic-copy"><p className="eyebrow">THE CHEF’S SHOWCASE · {index+1}/{entries.length}</p><h2>{entry.bowl.title||'A delicious original'}</h2><p>A fresh perspective. A little applause.</p><span>{entry.mine?'Your moment in the spotlight':'Chef identities stay hidden until results'}</span></div><div className="cinematic-bowl"><Bowl bowl={entry.bowl} autoOrbit/></div><div className="cinematic-applause"><RevealReactions room={room} ballot={entry.ballot} mine={entry.mine} onReact={kind=>onReact(entry.ballot,kind)}/></div></section>}
export function AchievementShelf({room,onChoose}:{room:View|null;onChoose:(patch:Partial<BowlData>)=>void}){const [earned,setEarned]=useState<string[]>([]),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();fetch('/api/game?profile=1',{signal:c.signal}).then(async r=>{const data=await r.json() as {error?:string;achievements:string[]};if(!r.ok)throw Error(data.error||'Rewards are unavailable.');setEarned(data.achievements);setError('')}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[room?.phase,room?.matchId]);return <section className="achievement-shelf"><div><p className="eyebrow"><Trophy size={16}/> YOUR SIGNATURE COLLECTION</p><h2>Make something worth remembering.</h2><p>Earn achievements in multiplayer matches. Rewards unlock when the match finishes.</p></div>{error&&<p role="status">{error}</p>}<div className="achievement-grid">{ACHIEVEMENTS.map(a=>{const unlocked=earned.includes(a.id);return <article className={unlocked?'achievement-earned':''} key={a.id}><span className="achievement-medal">{unlocked?<Trophy/>:<Lock/>}</span><h3>{a.name}</h3><p>{a.description}</p><strong>{a.reward}</strong><Button disabled={!unlocked} onClick={()=>{const patch=a.id==='berry'?{finish:'mosaic'}:a.id==='perfect'?{countertop:'marble'}:{effect:'lustre'};localStorage.setItem(`acai-reward-${a.id}`,JSON.stringify(patch));if(a.id==='berry')localStorage.setItem('acai-finish','mosaic');onChoose(patch)}}>{unlocked?'Use reward':'Keep creating'}</Button></article>})}</div></section>}
