import {FANTASY_INGREDIENTS} from './fantasy-ingredients.ts';
import type {Bowl} from './game';
export const SURPRISE_DELAY_MS=60_000;
export const ORDERS=[
{id:'tropical',customer:'Isla',title:'A little island escape',requests:['Use mango','Add a crunchy topping','Leave out chocolate'],ingredients:['mango','crunch','no-chocolate']},
{id:'berry',customer:'Nova',title:'Berry beautiful',requests:['Use strawberries','Add blueberries','Finish with a drizzle'],ingredients:['strawberry','blueberry','drizzle']},
{id:'green',customer:'Sage',title:'Fresh from the garden',requests:['Use kiwi','Add pistachio','Leave out chocolate'],ingredients:['kiwi','pistachio','no-chocolate']},
{id:'sunrise',customer:'Sol',title:'Sunrise breakfast',requests:['Use banana','Add granola','Finish with honey'],ingredients:['banana','granola','honey']},
{id:'dessert',customer:'Coco',title:'A sweet little indulgence',requests:['Use strawberries','Add chocolate chips','Finish with chocolate sauce'],ingredients:['strawberry','chocolate','cocoa']},
{id:'wizard',customer:'Merlin',title:'A spell worth tasting',requests:['Use a fantasy ingredient','Add a crunchy topping','Finish with a drizzle'],ingredients:['fantasy','crunch','drizzle']},
{id:'critic',customer:'Margot',title:'The critic’s clean classic',requests:['Use strawberries','Add almond slivers','Leave out drizzle'],ingredients:['strawberry','almond','no-drizzle']},
{id:'fanatic',customer:'Pip',title:'Fruit first. Fruit forever.',requests:['Use three different fruits','Use pineapple','Leave out chocolate'],ingredients:['fruit-variety','pineapple','no-chocolate']},
{id:'stargazer',customer:'Lyra',title:'Midnight at the fruit bar',requests:['Use Moonberries','Add Starflakes','Give the bowl a name'],ingredients:['moonberry','starflake','name']},
{id:'crunch-club',customer:'Otis',title:'The crunch club special',requests:['Use granola','Add pistachio','Use any fruit'],ingredients:['granola','pistachio','fruit']},
{id:'simple',customer:'Remy',title:'Small bowl, big personality',requests:['Use any fruit','Add a crunchy topping','Give the bowl a name'],ingredients:['fruit','crunch','name']}
] as const;
export const TWISTS=[{id:'symmetry',name:'A little balance',description:'Create at least three matching pairs across the center.'},{id:'green',name:'Fresh green finish',description:'Place at least three pieces of kiwi or pistachio.'},{id:'pink',name:'Pretty in pink',description:'Place at least three strawberries, raspberries, or dragonfruit pieces.'},{id:'smile',name:'A fruity smile',description:'Place five fruits in the lower arc and two fruits above them as eyes.'},{id:'handmade',name:'Made by hand',description:'Slice a fruit, spread the base, and draw a freehand drizzle.'}] as const;
const FRUIT=['strawberry','banana','mango','blueberry','kiwi','raspberry','pineapple','dragonfruit',...FANTASY_INGREDIENTS.filter(v=>v.category==='Fruit').map(v=>v.id)];
const CRUNCH=['granola','coconut','almond','cacao','chia','pistachio','chocolate',...FANTASY_INGREDIENTS.filter(v=>v.category==='Crunch').map(v=>v.id)];
const SAUCE=['honey','cocoa','peanut','vanilla',...FANTASY_INGREDIENTS.filter(v=>v.category==='Drizzle').map(v=>v.id)];
export function orderProgress(b:Bowl,id:string){const o=ORDERS.find(v=>v.id===id);return (o?.ingredients||[]).map(rule=>rule==='fantasy'?b.pieces.some(p=>FANTASY_INGREDIENTS.some(i=>i.id===p.id)):rule==='fruit-variety'?new Set(b.pieces.filter(p=>FRUIT.includes(p.id)).map(p=>p.id)).size>=3:rule==='no-drizzle'?!b.pieces.some(p=>SAUCE.includes(p.id)):rule==='crunch'?b.pieces.some(p=>CRUNCH.includes(p.id)):rule==='fruit'?b.pieces.some(p=>FRUIT.includes(p.id)):rule==='drizzle'?b.pieces.some(p=>SAUCE.includes(p.id)):rule==='name'?b.title.trim().length>=3:rule==='no-chocolate'?!b.pieces.some(p=>['chocolate','cocoa','cacao'].includes(p.id)):b.pieces.some(p=>p.id===rule));}
export function twistProgress(b:Bowl,id:string){if(id==='handmade')return !!b.prepared?.length&&!!b.spread?.length&&b.pieces.some(p=>!!p.path?.length);if(id==='green'||id==='pink')return b.pieces.filter(p=>(id==='green'?['kiwi','pistachio']:['strawberry','raspberry','dragonfruit']).includes(p.id)).length>=3;if(id==='smile')return b.pieces.filter(p=>FRUIT.includes(p.id)&&p.y>55&&Math.abs(p.x-50)<28).length>=5&&b.pieces.filter(p=>FRUIT.includes(p.id)&&p.y<45).length>=2;const used=new Set<number>();let pairs=0;for(const p of b.pieces.filter(p=>p.x<46)){const j=b.pieces.findIndex((q,j)=>!used.has(j)&&q.x>54&&q.id===p.id&&Math.hypot(q.x-(100-p.x),q.y-p.y)<6);if(j>=0){used.add(j);pairs++;}}return pairs>=3;}
export const ACHIEVEMENTS=[{id:'berry',name:'Berry Artist',description:'Use five different fruit types in a multiplayer bowl.',reward:'Mosaic porcelain bowl'},{id:'perfect',name:'Perfect Order',description:'Fulfil all three customer requests in one round.',reward:'Rose marble countertop'},{id:'crowd',name:'Crowd Favorite',description:'Win three audience awards across completed matches.',reward:'Lustre drizzle finish'}] as const;
export function bowlAchievements(b:Bowl,order?:string){const a:string[]=[];if(new Set(b.pieces.filter(p=>FRUIT.includes(p.id)).map(p=>p.id)).size>=5)a.push('berry');const p=orderProgress(b,order||'');if(p.length&&p.every(Boolean))a.push('perfect');return a;}

export const CUSTOMER_PERSONALITIES:Record<string,{role:string;quote:string;color:string;success:string;partial:string}>={
 tropical:{role:'Island explorer',quote:'Bring me sunshine, a little crunch, and an island escape.',color:'sunshine',success:'That tastes like a holiday. Save me a seat!',partial:'A little more island sunshine next time.'},
 berry:{role:'Berry enthusiast',quote:'Make the berries the stars. I love a sweet finishing ribbon.',color:'berry',success:'Berry beautiful! That is my kind of bowl.',partial:'The berries are calling for their supporting cast.'},
 green:{role:'Garden enthusiast',quote:'Fresh, green, and gently crunchy. That is my happy place.',color:'garden',success:'Fresh as a morning in the garden.',partial:'My garden needs a little more green.'},
 sunrise:{role:'Early bird',quote:'Banana, granola, honey. My morning ritual, made beautiful.',color:'sunshine',success:'Now that is a very good morning.',partial:'Almost breakfast heaven. Check my morning trio.'},
 dessert:{role:'Dessert dreamer',quote:'My sweet tooth voted for chocolate before I even arrived.',color:'berry',success:'Dessert dreams do come true.',partial:'There is still room for a sweeter finish.'},
 simple:{role:'Small-bowl specialist',quote:'Keep it simple. Three thoughtful choices beat a hundred random ones.',color:'garden',success:'Small bowl. Huge personality. Beautifully done.',partial:'Keep it thoughtful and check my three little requests.'},
 wizard:{role:'Fantasy-loving wizard',quote:'Ordinary fruit is lovely. But I am here for edible magic.',color:'magic',success:'A delicious spell! The bowl is enchanted.',partial:'Promising potion. A little more magic, please.'},
 critic:{role:'Picky café critic',quote:'No drizzle distractions. Let the fruit and almond do the talking.',color:'berry',success:'Precise. Restrained. I approve.',partial:'An interesting start. My checklist is quite specific.'},
 fanatic:{role:'Fruit fanatic',quote:'One fruit is a snack. Three fruits are a party.',color:'sunshine',success:'A whole fruit party in one bowl!',partial:'Invite a few more fruits to the party.'},
 stargazer:{role:'Midnight stargazer',quote:'Moonberries, star crunch, and a name written in the sky.',color:'magic',success:'That bowl belongs among the stars.',partial:'A constellation still waiting for its last stars.'},
 'crunch-club':{role:'Crunch collector',quote:'Granola and pistachio. I am listening for the perfect crunch.',color:'garden',success:'That crunch deserves an encore.',partial:'My crunch club is missing a member.'}
};
